const C=window.LARACHEDEV_CONFIG||{};let session=JSON.parse(localStorage.getItem("larachedev_session")||"null"),selected=null,branch=C.branch||"main";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
async function api(p,o={}){const r=await fetch(C.supabaseUrl+"/rest/v1/"+p,{...o,headers:{apikey:C.supabasePublishableKey,Authorization:"Bearer "+session.access_token,"Content-Type":"application/json",...(o.headers||{})}});if(!r.ok)throw Error(await r.text());return r.status===204?null:r.json()}
async function gh(a,q={}){const r=await fetch(C.githubManager+"?action="+a+"&"+new URLSearchParams(q),{headers:{apikey:C.supabasePublishableKey,Authorization:"Bearer "+session.access_token}});const j=await r.json();if(!r.ok)throw Error(j.error||JSON.stringify(j));return j}
function initTabs(){const b=$$(".tabs button"),v=$$(".tab");b.forEach(x=>x.onclick=async()=>{b.forEach(y=>y.classList.remove("active"));x.classList.add("active");v.forEach(y=>y.hidden=y.id!=="tab-"+x.dataset.tab);if(x.dataset.tab==="files")loadFiles();if(x.dataset.tab==="github")loadGitHub();if(x.dataset.tab==="supabase")loadSupabase();if(x.dataset.tab==="audit")loadAudit()})}
async function start(){if(!session)return;try{const a=await api("admin_users?select=role,enabled&user_id=eq."+encodeURIComponent(session.user.id));if(!a[0]?.enabled)throw Error("المستخدم غير موجود في admin_users.");$("#loginView").hidden=true;$("#dashboardView").hidden=false;$("#logoutBtn").hidden=false;$("#githubStatus").textContent="متصل";$("#overviewMsg").textContent="الدور: "+a[0].role;initTabs();await loadGitHub()}catch(e){localStorage.removeItem("larachedev_session");session=null;$("#loginMsg").textContent=e.message}}
$("#loginForm").onsubmit=async e=>{e.preventDefault();try{const r=await fetch(C.supabaseUrl+"/auth/v1/token?grant_type=password",{method:"POST",headers:{apikey:C.supabasePublishableKey,"Content-Type":"application/json"},body:JSON.stringify({email:$("#email").value.trim(),password:$("#password").value})});const j=await r.json();if(!r.ok)throw Error(j.error_description||j.msg||"فشل الدخول");session=j;localStorage.setItem("larachedev_session",JSON.stringify(j));await start()}catch(e){$("#loginMsg").textContent=e.message}};
$("#logoutBtn").onclick=()=>{localStorage.removeItem("larachedev_session");location.reload()};
$("#refreshFrame").onclick=()=>{const f=$("#siteFrame");f.src=f.src};
async function loadFiles(){try{const b=await gh("branches");$("#branchSelect").innerHTML=b.map(x=>"<option>"+x.name+"</option>").join("");$("#branchSelect").value=branch;const t=await gh("tree",{ref:branch});$("#tree").innerHTML=(t.tree||[]).filter(x=>x.type==="blob").map(x=>"<div class=file-item data-path='"+x.path+"'>"+x.path+"</div>").join("");$$(".file-item").forEach(x=>x.onclick=()=>openFile(x.dataset.path))}catch(e){$("#tree").textContent=e.message}}
async function openFile(p){try{const f=await gh("file",{path:p,ref:branch});selected={path:p,sha:f.sha};$("#fileTitle").textContent=p;const raw=atob((f.content||"").replace(/\n/g,""));$("#editor").value=decodeURIComponent(escape(raw));$("#fileMsg").textContent=""}catch(e){$("#fileMsg").textContent=e.message}}
async function loadGitHub(){try{const [b,c,r,rel]=await Promise.all([gh("branches"),gh("commits"),gh("runs"),gh("releases")]);$("#branchesCount").textContent=b.length;$("#commitsCount").textContent=c.length;$("#runsCount").textContent=r.total_count||0;$("#releasesCount").textContent=rel.length;$("#commits").innerHTML=c.map(x=>"<p><b>"+x.sha.slice(0,7)+"</b> "+(x.commit.message||"").split("\n")[0]+"</p>").join("")}catch(e){$("#commits").textContent=e.message}}
async function loadSupabase(){try{const s=await api("site_settings?select=key,value,updated_at&order=key");$("#settingsData").innerHTML=s.map(x=>"<p><b>"+x.key+"</b>: "+JSON.stringify(x.value)+"</p>").join("")}catch(e){$("#settingsData").textContent=e.message}}
async function loadAudit(){try{const a=await api("audit_logs?select=*&order=created_at.desc&limit=100");$("#auditData").innerHTML=a.map(x=>"<p><b>"+x.action+"</b> — "+(x.resource||"")+"</p>").join("")}catch(e){$("#auditData").textContent=e.message}}
$("#reloadTree").onclick=loadFiles;$("#branchSelect").onchange=e=>{branch=e.target.value;loadFiles()};$("#saveFile").onclick=async()=>{if(!selected){$("#fileMsg").textContent="اختر ملفًا.";return}try{const r=await fetch(C.githubManager+"?action=write-file",{method:"POST",headers:{apikey:C.supabasePublishableKey,Authorization:"Bearer "+session.access_token,"Content-Type":"application/json"},body:JSON.stringify({path:selected.path,content:$("#editor").value,branch,message:$("#commitMessage").value||"admin: update "+selected.path})});const j=await r.json();if(!r.ok)throw Error(j.error||JSON.stringify(j));$("#fileMsg").textContent="تم إنشاء Commit: "+(j.commit?.sha||"OK");await loadFiles()}catch(e){$("#fileMsg").textContent=e.message}};$("#newFile").onclick=()=>{const p=prompt("مسار الملف:");if(p){selected={path:p};$("#fileTitle").textContent=p;$("#editor").value=""}};start();